#ifndef MODBUS_FUNCTION_CODES_H
#define MODBUS_FUNCTION_CODES_H

#define MASTER_ID 0x00

#define COILS 1
#define HOLDING_REGISTERS 2
#define INPUT_REGISTERS 3
#define DISCRETE_INPUTS 4

#define WRITE_SINGLE_COIL_FUNCTIONCODE 0x05
#define WRITE_SINGLE_REGISTER_FUNCTIONCODE 0x06
#define READ_COILS_FUNCTIONCODE 0x01
#define READ_INPUT_REGISTERS_FUNCTIONCODE 0x04

#define WRITE_MULTIPLE_REGISTERS_FUNCTIONCODE  0x10 //*1
#define READ_DISCRETE_INPUTS_FUNCTIONCODE  0x02 //*2
#define WRITE_MULTIPLE_COILS_FUNCTIONCODE  0x0f
#define READ_HOLDING_REGISTERS_FUNCTIONCODE  0x03 //*1


#define INVALID_FUNCTION_CODE_EXCEPTION_CODE 0x01
#define INVALID_DATA_ADDRESS_EXCEPTION_CODE 0x02
#define INVALID_DATA_VALUE_EXCEPTION_CODE 0x03
#define EXECUTION_PROBLEM_EXCEPTION_CODE 0x04


#define COIL_VALUE_SET 0xFF
#define COIL_VALUE_RESET 0x00
#define COIL_VALUE_ERROR 0x80

#define EXCEPTION_OFFSET 0x80

#define PARSER_REGISTERS_BUFFER_SIZE 25
#define PARSER_DIGITALS_BUFFER_SIZE 400

#endif